//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Proxydomo.RC
//


#define IDD_ABOUTBOX				100
#define IDR_MAINFRAME				128
//#define IDR_PROXYDOMOTYPE	129
#define IDD_MAINDLG				129
#define	IDD_LOGVIEW				130
#define IDD_FILTERMANAGE		131
#define IDD_FILTEREDIT			132
#define IDD_FILTERTEST			133
#define IDD_LISTEDIT			134

#define IDC_RICHEDIT_LOG		1000
#define IDC_BUTTON_CLEAR		1001
#define IDC_BUTTON_SHOWLOGWINDOW	1002
#define IDC_BUTTON_SHOWACTIVEREQUESTLOG	1003
#define IDC_TREE_FILTER			1004
#define IDC_BUTTON_ADDFILTER	1005
#define IDC_BUTTON_SHOWFILTERMANAGE	1006
#define IDC_EDIT_FILTERNAME			1007
#define IDC_EDIT_AUTHERNAME			1008
#define IDC_EDIT_VERSION			1009
#define IDC_EDIT_FILTERDISCRIPTION	1010
#define IDC_COMBO_FILTERTYPE		1011
#define IDC_EDIT_WINDOWWIDTH		1012
#define IDC_COMBO_HEADERNAME		1013
#define IDC_CHECKBOX_MULTIPLEMUTCH	1014
#define IDC_EDIT_URLPATTERN			1015
#define IDC_EDIT_BOUNDSPATTERN		1016
#define IDC_EDIT_MATCHPATTERN		1017
#define IDC_EDIT_REPLACEPATTERN		1018
#define IDC_BUTTON_TEST				1019
#define IDC_EDIT_TESTTEXT			1020
#define IDC_EDIT_RESULTTEXT			1021
#define IDC_BUTTON_ANALYZE			1022
#define IDC_BUTTON_REFRESH			1023
#define IDC_BUTTON_IMPORTFROMPROXOMITRON	1024
#define IDC_BUTTON_DELETEFILTER		1025
#define IDC_BUTTON_ADDNEWLIST		1026
#define IDC_LIST					1027
#define IDC_BUTTON_DELETELIST		1028
#define IDC_BUTTON_SHOWLISTEDIT		1029
#define IDC_EDIT_PROXYPORT			1030
#define IDC_CHECKBOX_WEBPAGE		1031
#define IDC_CHECKBOX_OUTHEADER		1032
#define IDC_CHECKBOX_INHEADER		1033
#define IDC_STATIC_VERSION			1034
#define IDC_STATIC_LIMIT			1035
#define IDC_STATIC_BOUNDS			1036
#define IDC_STATIC_REPLACE			1037
#define IDC_STATIC_APP				1038


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	201
#define _APS_NEXT_CONTROL_VALUE		1100
#define _APS_NEXT_SYMED_VALUE		140
#define _APS_NEXT_COMMAND_VALUE		32775
#endif
#endif
